name: radio_vision
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.6.1
  just_audio: ^0.9.29
  intl: ^0.18.0
  http: ^0.13.5
  url_launcher: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/casque.jpg
    - assets/logo1.png  
    - assets/radio_placeholder.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo1.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo1.png"
